export const WELCOME = "WELCOME";
export const NEW_SITUATION = "NEW_SITUATION";
export const USER_MADE_DECISION = "USER_MADE_DECISION";
export const GAME_IS_ON_LAST_QUESTION = "GAME_IS_ON_LAST_QUESTION";